package backend

import (
	"fmt"
	"math"
	"strconv"
	"strings"

	"github.com/zobstory/cakebear/ir"
)

// rtPkg is the import alias for cakebear's runtime inside generated code.
// Deliberately unlovely: it shares a namespace with mangled user identifiers,
// and a user variable called `rt` should not be able to shadow it.
const rtPkg = "cakebearrt"

// emitter builds Go source from the IR.
//
// Source text is written directly rather than assembled as a go/ast tree and
// printed. The emitter runs on every build, the output is immediately handed to
// a real Go parser that will reject anything malformed, and a tree buys nothing
// here but allocations.
type emitter struct {
	buf strings.Builder
	// usesRuntime records whether anything actually called into the runtime.
	// An unused import is a compile error in Go, so this decides whether the
	// import gets written at all.
	usesRuntime bool
}

// Emit renders a module as the contents of a Go main package.
func Emit(m *ir.Module) string {
	var e emitter

	// The body is emitted first so usesRuntime is known before the header,
	// which is what decides whether the runtime import appears.
	body := e.module(m)

	var out strings.Builder
	out.WriteString("// Code generated by cakec. DO NOT EDIT.\n")
	out.WriteString("//\n")
	fmt.Fprintf(&out, "// Source: %s\n\n", m.Name)
	out.WriteString("package main\n\n")
	if e.usesRuntime {
		fmt.Fprintf(&out, "import %s %q\n\n", rtPkg, genModule+"/"+rtDir)
	}
	out.WriteString(body)
	return out.String()
}

func (e *emitter) module(m *ir.Module) string {
	// Functions and main are rendered into separate buffers before anything is
	// assembled, because whether the runtime is used at all is only known once
	// every statement has been walked -- a program whose only output comes from
	// inside a called function still needs the buffer flushed, and a program
	// that never logs must not import the runtime, since Go rejects an unused
	// import.
	funcs := e.capture(func() {
		for _, fn := range m.Funcs {
			e.function(fn)
			e.buf.WriteString("\n")
		}
	})
	mainBody := e.capture(func() {
		e.stmts(m.Main, 1)
	})

	var out strings.Builder
	out.WriteString(funcs)
	out.WriteString("func main() {\n")
	if e.usesRuntime {
		out.WriteString("\tdefer " + rtPkg + ".Flush()\n")
	}
	out.WriteString(mainBody)
	out.WriteString("}\n")
	return out.String()
}

// capture runs an emit step against a fresh buffer and returns what it wrote,
// leaving e.usesRuntime accumulated across calls.
func (e *emitter) capture(emit func()) string {
	saved := e.buf
	e.buf = strings.Builder{}
	emit()
	written := e.buf.String()
	e.buf = saved
	return written
}

func (e *emitter) function(fn *ir.Func) {
	fmt.Fprintf(&e.buf, "func %s(", mangle(fn.Name))
	for i, p := range fn.Params {
		if i > 0 {
			e.buf.WriteString(", ")
		}
		fmt.Fprintf(&e.buf, "%s %s", mangle(p.Name), goType(p.Type))
	}
	e.buf.WriteString(")")
	if fn.Result != ir.Void {
		fmt.Fprintf(&e.buf, " %s", goType(fn.Result))
	}
	e.buf.WriteString(" {\n")
	e.stmts(fn.Body, 1)
	e.buf.WriteString("}\n")
}

func (e *emitter) stmts(stmts []ir.Stmt, depth int) {
	for _, s := range stmts {
		e.stmt(s, depth)
	}
}

func (e *emitter) stmt(s ir.Stmt, depth int) {
	pad := strings.Repeat("\t", depth)

	switch s := s.(type) {
	case *ir.VarDecl:
		// An explicit type rather than := because TypeScript's annotation is
		// the authority here, and := would let Go's inference disagree with it.
		fmt.Fprintf(&e.buf, "%svar %s %s = %s\n", pad, mangle(s.Name), goType(s.Type), e.expr(s.Init))
		// Go rejects unused locals; TypeScript does not. Referencing the
		// variable keeps a legal TypeScript program from failing to build.
		fmt.Fprintf(&e.buf, "%s_ = %s\n", pad, mangle(s.Name))

	case *ir.Assign:
		fmt.Fprintf(&e.buf, "%s%s = %s\n", pad, mangle(s.Name), e.expr(s.Value))

	case *ir.If:
		fmt.Fprintf(&e.buf, "%sif %s {\n", pad, e.expr(s.Cond))
		e.stmts(s.Then, depth+1)
		if len(s.Else) > 0 {
			fmt.Fprintf(&e.buf, "%s} else {\n", pad)
			e.stmts(s.Else, depth+1)
		}
		fmt.Fprintf(&e.buf, "%s}\n", pad)

	case *ir.While:
		fmt.Fprintf(&e.buf, "%sfor %s {\n", pad, e.expr(s.Cond))
		e.stmts(s.Body, depth+1)
		fmt.Fprintf(&e.buf, "%s}\n", pad)

	case *ir.Return:
		if s.Value == nil {
			fmt.Fprintf(&e.buf, "%sreturn\n", pad)
		} else {
			fmt.Fprintf(&e.buf, "%sreturn %s\n", pad, e.expr(s.Value))
		}

	case *ir.ExprStmt:
		fmt.Fprintf(&e.buf, "%s%s\n", pad, e.expr(s.Expr))

	default:
		// Unreachable: ir.Stmt is a closed interface. Emitting a compile error
		// beats emitting silence, because silence would produce a program that
		// builds and quietly does less than the source said.
		fmt.Fprintf(&e.buf, "%s#error unhandled statement %T\n", pad, s)
	}
}

func (e *emitter) expr(x ir.Expr) string {
	switch x := x.(type) {
	case *ir.NumberLit:
		if x.Value == 0 && math.Signbit(x.Value) {
			// See runtime.NegZero: this value has no literal spelling in Go.
			e.usesRuntime = true
			return rtPkg + ".NegZero"
		}
		return goFloat(x.Value)

	case *ir.StringLit:
		return strconv.Quote(x.Value)

	case *ir.BoolLit:
		return strconv.FormatBool(x.Value)

	case *ir.NullLit, *ir.UndefinedLit:
		// Phase 1 has no nullable representation yet: null and undefined can be
		// written but not stored in a typed binding, so nothing should reach
		// here. lower/ rejects them first.
		return "nil"

	case *ir.Ident:
		return mangle(x.Name)

	case *ir.Binary:
		return e.binary(x)

	case *ir.Unary:
		return fmt.Sprintf("(%s%s)", goUnaryOp(x.Op), e.expr(x.Operand))

	case *ir.Call:
		args := make([]string, len(x.Args))
		for i, a := range x.Args {
			args[i] = e.expr(a)
		}
		return fmt.Sprintf("%s(%s)", mangle(x.Callee), strings.Join(args, ", "))

	case *ir.ConsoleLog:
		e.usesRuntime = true
		return fmt.Sprintf("%s.%s(%s)", rtPkg, logFunc(x.Arg.ExprType()), e.expr(x.Arg))

	default:
		return fmt.Sprintf("#error unhandled expression %T", x)
	}
}

func (e *emitter) binary(x *ir.Binary) string {
	return fmt.Sprintf("(%s %s %s)", e.expr(x.Left), goBinaryOp(x.Op), e.expr(x.Right))
}

// goFloat renders a TypeScript number as a Go float64 literal.
//
// The suffix matters: Go would treat a bare `5` in a float64 context as an
// untyped constant, which usually works but silently changes meaning in
// division -- `5 / 2` is 2 as integer constants and 2.5 as floats, and
// TypeScript means 2.5.
func goFloat(f float64) string {
	s := strconv.FormatFloat(f, 'g', -1, 64)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

func goType(t ir.Type) string {
	switch t {
	case ir.Number:
		return "float64"
	case ir.String:
		return "string"
	case ir.Boolean:
		return "bool"
	default:
		return "any"
	}
}

func logFunc(t ir.Type) string {
	switch t {
	case ir.Number:
		return "LogNumber"
	case ir.String:
		return "LogString"
	case ir.Boolean:
		return "LogBool"
	case ir.Null:
		return "LogNull"
	default:
		return "LogUndefined"
	}
}

func goBinaryOp(op ir.BinaryOp) string {
	switch op {
	case ir.OpAdd:
		return "+"
	case ir.OpSub:
		return "-"
	case ir.OpMul:
		return "*"
	case ir.OpDiv:
		return "/"
	case ir.OpLess:
		return "<"
	case ir.OpLessEq:
		return "<="
	case ir.OpGreater:
		return ">"
	case ir.OpGreaterEq:
		return ">="
	case ir.OpEqual:
		return "=="
	case ir.OpNotEqual:
		return "!="
	case ir.OpAnd:
		return "&&"
	case ir.OpOr:
		return "||"
	default:
		return "?"
	}
}

func goUnaryOp(op ir.UnaryOp) string {
	if op == ir.OpNeg {
		return "-"
	}
	return "!"
}
