package backend

import (
	"fmt"
	"math"
	"strconv"
	"strings"

	"github.com/zobstory/cakebear/ir"
)

// rtPkg is the import alias for cakebear's runtime inside generated code.
// Deliberately unlovely: it shares a namespace with mangled user identifiers,
// and a user variable called `rt` should not be able to shadow it.
const rtPkg = "cakebearrt"

// emitter builds Go source from the IR.
//
// Source text is written directly rather than assembled as a go/ast tree and
// printed. The emitter runs on every build, the output is immediately handed to
// a real Go parser that will reject anything malformed, and a tree buys nothing
// here but allocations.
type emitter struct {
	buf strings.Builder
	// usesRuntime records whether anything actually called into the runtime.
	// An unused import is a compile error in Go, so this decides whether the
	// import gets written at all.
	usesRuntime bool
	// depth is the indentation of the statement being emitted, so a function
	// literal inside one of its expressions can indent its body to match.
	depth int
	// unsupported collects IR this backend cannot emit yet. Build refuses the
	// module before go build ever sees the placeholder written for each.
	unsupported []Unsupported
	// usesHost records a call into node:http. Such a program ends main with the
	// runtime's Run, which keeps the process alive while a server listens.
	usesHost bool
	// hoisted holds the top-level variables declared at package level. Their
	// declarations in main become assignments.
	hoisted map[*ir.VarDecl]bool
}

// Emit renders a module as the contents of a Go main package. IR the backend
// cannot emit yet appears as an #error line; Build reports it properly.
func Emit(m *ir.Module) string {
	src, _ := emit(m)
	return src
}

func emit(m *ir.Module) (string, []Unsupported) {
	var e emitter

	// The body is emitted first so usesRuntime is known before the header,
	// which is what decides whether the runtime import appears.
	body := e.module(m)

	var out strings.Builder
	out.WriteString("// Code generated by cakec. DO NOT EDIT.\n")
	out.WriteString("//\n")
	fmt.Fprintf(&out, "// Source: %s\n\n", m.Name)
	out.WriteString("package main\n\n")
	if e.usesRuntime {
		fmt.Fprintf(&out, "import %s %q\n\n", rtPkg, genModule+"/"+rtDir)
	}
	out.WriteString(body)
	return out.String(), sortedUnsupported(e.unsupported)
}

func (e *emitter) module(m *ir.Module) string {
	// Functions and main are rendered into separate buffers before anything is
	// assembled, because whether the runtime is used at all is only known once
	// every statement has been walked -- a program whose only output comes from
	// inside a called function still needs the buffer flushed, and a program
	// that never logs must not import the runtime, since Go rejects an unused
	// import.
	//
	// Top-level variables are declared at package level, so a top-level
	// function can use them, and assigned where the source initialises them, so
	// side effects keep their order. A package-level initialiser would run
	// before main, ahead of any top-level code written earlier in the file.
	e.hoisted = map[*ir.VarDecl]bool{}
	globals := e.capture(func() {
		for _, s := range m.Main {
			if d, ok := s.(*ir.VarDecl); ok {
				fmt.Fprintf(&e.buf, "var %s %s\n", mangle(d.Name), e.typ(d.Type))
				e.hoisted[d] = true
			}
		}
	})
	funcs := e.capture(func() {
		for _, fn := range m.Funcs {
			e.function(fn)
			e.buf.WriteString("\n")
		}
	})
	mainBody := e.capture(func() {
		e.stmts(m.Main, 1)
	})

	var out strings.Builder
	if globals != "" {
		out.WriteString(globals + "\n")
	}
	out.WriteString(funcs)
	out.WriteString("func main() {\n")
	if e.usesRuntime {
		out.WriteString("\tdefer " + rtPkg + ".Flush()\n")
	}
	out.WriteString(mainBody)
	if e.usesHost {
		// Last, so listen callbacks run after the top-level code, as in Node.
		out.WriteString("\t" + rtPkg + ".Run()\n")
	}
	out.WriteString("}\n")
	return out.String()
}

// capture runs an emit step against a fresh buffer and returns what it wrote,
// leaving e.usesRuntime accumulated across calls.
func (e *emitter) capture(emit func()) string {
	saved := e.buf
	e.buf = strings.Builder{}
	emit()
	written := e.buf.String()
	e.buf = saved
	return written
}

func (e *emitter) function(fn *ir.Func) {
	fmt.Fprintf(&e.buf, "func %s(", mangle(fn.Name))
	for i, p := range fn.Params {
		if i > 0 {
			e.buf.WriteString(", ")
		}
		fmt.Fprintf(&e.buf, "%s %s", mangle(p.Name), e.typ(p.Type))
	}
	e.buf.WriteString(")")
	if fn.Result != ir.Void {
		fmt.Fprintf(&e.buf, " %s", e.typ(fn.Result))
	}
	e.buf.WriteString(" {\n")
	e.stmts(fn.Body, 1)
	e.buf.WriteString("}\n")
}

func (e *emitter) stmts(stmts []ir.Stmt, depth int) {
	for _, s := range stmts {
		e.stmt(s, depth)
	}
}

func (e *emitter) stmt(s ir.Stmt, depth int) {
	pad := strings.Repeat("\t", depth)
	e.depth = depth

	switch s := s.(type) {
	case *ir.VarDecl:
		if e.hoisted[s] {
			// Declared at package level already; see module.
			fmt.Fprintf(&e.buf, "%s%s = %s\n", pad, mangle(s.Name), e.expr(s.Init))
			return
		}
		if s.Type.Kind == ir.KindFunc {
			// Declared before it is assigned, so a function literal can call
			// itself. Go's scope for `var f = …` starts after the initialiser;
			// JavaScript's starts at the declaration.
			fmt.Fprintf(&e.buf, "%svar %s %s\n", pad, mangle(s.Name), e.typ(s.Type))
			fmt.Fprintf(&e.buf, "%s%s = %s\n", pad, mangle(s.Name), e.expr(s.Init))
		} else {
			// An explicit type rather than := because TypeScript's annotation
			// is the authority here, and := would let Go's inference disagree.
			fmt.Fprintf(&e.buf, "%svar %s %s = %s\n", pad, mangle(s.Name), e.typ(s.Type), e.expr(s.Init))
		}
		// Go rejects unused locals; TypeScript does not. Referencing the
		// variable keeps a legal TypeScript program from failing to build.
		fmt.Fprintf(&e.buf, "%s_ = %s\n", pad, mangle(s.Name))

	case *ir.Assign:
		fmt.Fprintf(&e.buf, "%s%s = %s\n", pad, mangle(s.Name), e.expr(s.Value))

	case *ir.If:
		fmt.Fprintf(&e.buf, "%sif %s {\n", pad, e.expr(s.Cond))
		e.stmts(s.Then, depth+1)
		if len(s.Else) > 0 {
			fmt.Fprintf(&e.buf, "%s} else {\n", pad)
			e.stmts(s.Else, depth+1)
		}
		fmt.Fprintf(&e.buf, "%s}\n", pad)

	case *ir.While:
		fmt.Fprintf(&e.buf, "%sfor %s {\n", pad, e.expr(s.Cond))
		e.stmts(s.Body, depth+1)
		fmt.Fprintf(&e.buf, "%s}\n", pad)

	case *ir.Return:
		if s.Value == nil {
			fmt.Fprintf(&e.buf, "%sreturn\n", pad)
		} else {
			fmt.Fprintf(&e.buf, "%sreturn %s\n", pad, e.expr(s.Value))
		}

	case *ir.ExprStmt:
		switch s.Expr.(type) {
		case *ir.Call, *ir.ConsoleLog, *ir.HostCall:
			fmt.Fprintf(&e.buf, "%s%s\n", pad, e.expr(s.Expr))
		default:
			// Go accepts only calls as expression statements, TypeScript any
			// expression: `x => x * 2` in a void slot evaluates and drops.
			fmt.Fprintf(&e.buf, "%s_ = %s\n", pad, e.expr(s.Expr))
		}

	default:
		// Recorded rather than skipped: silence would produce a program that
		// builds and quietly does less than the source said.
		e.unsupported = append(e.unsupported, Unsupported{Span: s.StmtSpan(), What: describeUnsupported(s)})
		fmt.Fprintf(&e.buf, "%s#error unhandled statement %T\n", pad, s)
	}
}

func (e *emitter) expr(x ir.Expr) string {
	switch x := x.(type) {
	case *ir.NumberLit:
		if x.Value == 0 && math.Signbit(x.Value) {
			// See runtime.NegZero: this value has no literal spelling in Go.
			e.usesRuntime = true
			return rtPkg + ".NegZero"
		}
		return goFloat(x.Value)

	case *ir.StringLit:
		return strconv.Quote(x.Value)

	case *ir.BoolLit:
		return strconv.FormatBool(x.Value)

	case *ir.NullLit, *ir.UndefinedLit:
		// Phase 1 has no nullable representation yet: null and undefined can be
		// written but not stored in a typed binding, so nothing should reach
		// here. lower/ rejects them first.
		return "nil"

	case *ir.Ident:
		return mangle(x.Name)

	case *ir.Binary:
		return e.binary(x)

	case *ir.Unary:
		return fmt.Sprintf("(%s%s)", goUnaryOp(x.Op), e.expr(x.Operand))

	case *ir.Convert:
		// A plain Go conversion. Truncation and wrapping follow Go's rules,
		// which are the machine's; the compile-time range check in types/
		// catches the literal cases before they get here.
		return fmt.Sprintf("%s(%s)", e.typ(x.Typ), e.expr(x.Value))

	case *ir.Call:
		args := make([]string, len(x.Args))
		for i, a := range x.Args {
			args[i] = e.expr(a)
		}
		return fmt.Sprintf("%s(%s)", mangle(x.Callee), strings.Join(args, ", "))

	case *ir.FuncLit:
		return e.funcLit(x)

	case *ir.HostCall:
		return e.hostCall(x)

	case *ir.HostProp:
		return e.hostProp(x)

	case *ir.ConsoleLog:
		e.usesRuntime = true
		return fmt.Sprintf("%s.%s(%s)", rtPkg, logFunc(x.Arg.ExprType()), e.expr(x.Arg))

	default:
		e.unsupported = append(e.unsupported, Unsupported{Span: x.ExprSpan(), What: describeUnsupported(x)})
		return fmt.Sprintf("#error unhandled expression %T", x)
	}
}

// funcLit renders a Go function literal. Go closures capture by reference, as
// JavaScript's do, so captured bindings need nothing beyond their names.
func (e *emitter) funcLit(x *ir.FuncLit) string {
	depth := e.depth
	params := make([]string, len(x.Params))
	for i, p := range x.Params {
		// An empty name is a parameter the literal ignores; mangle gives `_`.
		params[i] = mangle(p.Name) + " " + e.typ(p.Type)
	}
	body := e.capture(func() { e.stmts(x.Body, depth+1) })
	e.depth = depth

	result := ""
	if x.Result != ir.Void {
		result = " " + e.typ(x.Result)
	}
	return fmt.Sprintf("func(%s)%s {\n%s%s}", strings.Join(params, ", "), result, body, strings.Repeat("\t", depth))
}

func (e *emitter) binary(x *ir.Binary) string {
	return fmt.Sprintf("(%s %s %s)", e.expr(x.Left), goBinaryOp(x.Op), e.expr(x.Right))
}

// goFloat renders a TypeScript number as a Go float64 literal.
//
// The suffix matters: Go would treat a bare `5` in a float64 context as an
// untyped constant, which usually works but silently changes meaning in
// division -- `5 / 2` is 2 as integer constants and 2.5 as floats, and
// TypeScript means 2.5.
func goFloat(f float64) string {
	s := strconv.FormatFloat(f, 'g', -1, 64)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

func goType(t ir.Type) string {
	switch t.Kind {
	case ir.KindFunc:
		return goFuncType(t.Sig)
	case ir.KindHost:
		return goHostType(t.Host)
	}
	switch t {
	case ir.Number:
		return "float64"
	case ir.String:
		return "string"
	case ir.Boolean:
		return "bool"
	case ir.Int32:
		return "int32"
	case ir.Int64:
		return "int64"
	case ir.Uint32:
		return "uint32"
	case ir.Uint64:
		return "uint64"
	case ir.Float32:
		return "float32"
	case ir.Base64:
		// base64 is a compile-time refinement over string, not a distinct
		// runtime representation. See types/cakebear.d.ts.
		return "string"
	default:
		return "any"
	}
}

// goFuncType spells a function type: `func(float64, string) bool`.
func goFuncType(sig *ir.Signature) string {
	params := make([]string, len(sig.Params))
	for i, p := range sig.Params {
		params[i] = goType(p)
	}
	s := "func(" + strings.Join(params, ", ") + ")"
	if sig.Result != ir.Void {
		s += " " + goType(sig.Result)
	}
	return s
}

func logFunc(t ir.Type) string {
	switch t {
	case ir.Number:
		return "LogNumber"
	case ir.String:
		return "LogString"
	case ir.Boolean:
		return "LogBool"
	case ir.Null:
		return "LogNull"
	case ir.Int32:
		return "LogInt32"
	case ir.Int64:
		return "LogInt64"
	case ir.Uint32:
		return "LogUint32"
	case ir.Uint64:
		return "LogUint64"
	case ir.Float32:
		return "LogFloat32"
	case ir.Base64:
		return "LogString"
	default:
		return "LogUndefined"
	}
}

func goBinaryOp(op ir.BinaryOp) string {
	switch op {
	case ir.OpAdd:
		return "+"
	case ir.OpSub:
		return "-"
	case ir.OpMul:
		return "*"
	case ir.OpDiv:
		return "/"
	case ir.OpLess:
		return "<"
	case ir.OpLessEq:
		return "<="
	case ir.OpGreater:
		return ">"
	case ir.OpGreaterEq:
		return ">="
	case ir.OpEqual:
		return "=="
	case ir.OpNotEqual:
		return "!="
	case ir.OpAnd:
		return "&&"
	case ir.OpOr:
		return "||"
	default:
		return "?"
	}
}

func goUnaryOp(op ir.UnaryOp) string {
	if op == ir.OpNeg {
		return "-"
	}
	return "!"
}
